#!/usr/bin/env node
/**
 * Install local git hooks for this repository.
 *
 * Hooks installed:
 * - pre-commit: run web consistency checks
 * - pre-push: run web consistency checks
 */

const fs = require('fs');
const path = require('path');

const repoRoot = path.join(__dirname, '..', '..');
const hooksDir = path.join(repoRoot, '.git', 'hooks');

function writeHook(fileName, content) {
  const target = path.join(hooksDir, fileName);
  fs.writeFileSync(target, content, 'utf-8');
  try {
    fs.chmodSync(target, 0o755);
  } catch {
    // On Windows this may be ignored; Git will still run the script.
  }
  console.log(`Installed ${fileName}`);
}

function main() {
  if (!fs.existsSync(hooksDir)) {
    console.error('Cannot find .git/hooks. Run this inside the repository workspace.');
    process.exit(1);
  }

  const hookScript = `#!/bin/sh
# Auto-generated by web/scripts/install-hooks.js
set -e
REPO_ROOT=$(git rev-parse --show-toplevel)
cd "$REPO_ROOT/web"
npm run check:consistency
`;

  writeHook('pre-commit', hookScript);
  writeHook('pre-push', hookScript);

  console.log('Local git hooks installation complete.');
}

main();
